name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: Azure/k8s-bake@v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/charts'
          helm-version: 'latest'  
          overrides:  |
              bikes.image.tag: cf23df2207d99a74fbe169e3eba035e633b65d94                                                 
                                                
                            
      id: bake
