name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: azure/k8s-bake@v1

      with:

          renderEngine: 'helm2'

          helmChart: './samples/BikeSharingApp/charts'             
          helm-version: 'latest'           
          overrides: |
              bikes.image.repository:${{ secrets.CONTAINER_REGISTRY }}/bikes
              bikes.image.tag: ${{ github.sha }}
              billing.image.tag: ${{ github.sha }}
              users.image.tag: ${{ github.sha }}
              reservation.image.tag: ${{ github.sha }}
                                                
                            
      id: bake
