name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      
    - run: |
          'pwd'
          'helm dependency update'
          
    - uses: shigupt202/k8s-bake@releases/v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/charts'
          helm-version: 'latest'                                                   
                
                
                            
      id: bake
