name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      
    - uses: shigupt202/k8s-bake@releases/v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/charts/'
          helm-version: '3.0.1'
         
                
      id: bake
