name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: azure/k8s-bake@v1

      with:

          renderEngine: 'helm2'

          helmChart: './samples/BikeSharingApp/charts'             

          helmVersion: 'v3.0.2'                                           
                                                
                            
      id: bake
