name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
     
    - uses: azure/k8s-bake@users/shigupt/addingSilentInput

      with:

          renderEngine: 'helm2'

          helmChart: './samples/BikeSharingApp/charts'             
          helm-version: '3.0.0'           
          silent: 'false'
                                                                                                
               
               
      id: bake
