name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: Azure/k8s-bake@releases/v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/Bikes/charts/bikes/'
          helm-version: 'latest'                                                   
                                
                
                            
      id: bake
