name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      
    - name: Dependency update
      run: |
        helm init
        helm dependency update
      working-directory: ./samples/BikeSharingApp/charts
          
    - uses: shigupt202/k8s-bake@releases/v1
      with:
          renderEngine: 'helm2'
          helmChart: './samples/BikeSharingApp/charts'
          helm-version: 'latest'                                                   
                
                
                            
      id: bake
