name: Master

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master

    - uses: azure/k8s-bake@users/shigupt/addingSilentInput

      with:

          renderEngine: 'helm2'

          helmChart: './samples/BikeSharingApp/charts'             
          helm-version: 'latest'           
          overrides: |
                bikes.image.repository:${{ secrets.CONTAINER_REGISTRY }}/bikes
                bikes.image.tag:${{ github.sha }}
          silent: 'false'
                                                                                                
                            
      id: bake
